/*
 * (C) 2021; Joerg Fischer <georgi.rybakov@gmx.net>
 */
/**
 * entity classes for java persistence api.
 *
 * items herein are generated by netbeans 10.0 IDE.
 * that is why they will not be documented.
 *
 * @see <a href="http://netbeans.apache.org">netbeans IDE</a>
 */
package dom.jfischer.kaffeekasse.backend.database.entities;
